version: "3.8"

services:
#  api:
#    container_name: postgres-tutor-db
#    build: .
#    depends_on:
#      - postgres-container
#    ports:
#      - "8080:8080"
  postgres-tutor-db:
      container_name: postgres-tutor-db
      image: postgres:alpine
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=tutor-postgres-db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

