# Database Configuration

spring:
  datasource:
    url: postgresql://tutor-bakcend_owner:xQM3fPdRtN4e@ep-red-mode-a55hpw26.us-east-2.aws.neon.tech/tutor-bakcend?sslmode=require
    username: tutor-bakcend_owner
    password: xQM3fPdRtN4e
  jpa:
    open-in-view: false