# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutor-postgres-db
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    show-sql: true
