# Database Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutor-postgres-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

jwt:
  secret: W5Eca1S9aAf8l8Q6tVV1g5KrJyHUZ+BYi/GRpm1KhdQ=
  expiration: 20m
  refresh:
    expiration: 14d

