# Database Configuration

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tutor-postgres-db
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create