# Database Configuration

spring:
  data:
    mongodb:
      uri: mongodb+srv://shraierbohdan:9j4KkGxhiJB6VVq7@zno.refsfwm.mongodb.net/practice
  datasource:
    url: jdbc:postgresql://ep-red-mode-a55hpw26.us-east-2.aws.neon.tech/tutor-bakcend?user=tutor-bakcend_owner&password=xQM3fPdRtN4e&sslmode=require
    username: tutor-bakcend_owner
    password: xQM3fPdRtN4e
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  security:
    oauth2:
      resource-server:
        opaque-token:
            introspection-uri: https://www.googleapis.com/
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}

jwt:
  secret: W5Eca1S9aAf8l8Q6tVV1g5KrJyHUZ+BYi/GRpm1KhdQ=
  expiration: 20m
  refresh:
    expiration: 14d

  access-token-key: '{"kty":"oct","k":"hi7S5RX5ZRZooHA0RKGct  Z-KtR9FoESgCnH-3BNg5XI"}'
  refresh-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'
  cookie-token-key: '{"kty": "oct", "k": "OuX_DIOF1oBz8DKc7EJtOExC6oLUeQnotS6JsMps55c="}'

open-ai:
  key: ${GPT_KEY}
  url: https://api.openai.com/v1/chat/completions
  model: gpt-3.5-turbo


front-end:
  base-url: http://localhost:3000